"""Reporter — 生成测试报告"""

import base64
import os
import time
from datetime import datetime


REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — QualiAI 测试报告</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a10; color: #e8e8f0; padding: 40px; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  h1 {{ font-size: 24px; margin-bottom: 8px; }}
  .meta {{ color: #7b7f9b; font-size: 13px; margin-bottom: 30px; }}
  .summary {{ display: flex; gap: 20px; margin-bottom: 30px; }}
  .summary-card {{ flex: 1; padding: 20px; border-radius: 12px; background: #14141f; border: 1px solid #2a2a45; text-align: center; }}
  .summary-card .num {{ font-size: 32px; font-weight: 700; }}
  .summary-card .label {{ font-size: 12px; color: #7b7f9b; margin-top: 4px; }}
  .summary-card.pass {{ border-color: #22c55e; }} .summary-card.pass .num {{ color: #22c55e; }}
  .summary-card.fail {{ border-color: #ef4444; }} .summary-card.fail .num {{ color: #ef4444; }}
  .step {{ background: #14141f; border: 1px solid #2a2a45; border-radius: 12px; margin-bottom: 16px; overflow: hidden; }}
  .step-header {{ padding: 14px 18px; display: flex; align-items: center; gap: 12px; cursor: pointer; }}
  .step-header:hover {{ background: #1a1a2a; }}
  .step-icon {{ font-size: 20px; }}
  .step-info {{ flex: 1; }}
  .step-title {{ font-weight: 600; font-size: 14px; }}
  .step-desc {{ color: #7b7f9b; font-size: 12px; margin-top: 2px; }}
  .step-status {{ font-size: 12px; font-weight: 600; padding: 3px 10px; border-radius: 20px; }}
  .step-status.pass {{ background: #22c55e20; color: #22c55e; }}
  .step-status.fail {{ background: #ef444420; color: #ef4444; }}
  .step-body {{ padding: 0 18px 18px; display: none; }}
  .step-body.open {{ display: block; }}
  .step-body img {{ width: 100%; border-radius: 8px; border: 1px solid #2a2a45; margin-top: 10px; }}
  .step-detail {{ font-size: 12px; color: #7b7f9b; margin-top: 8px; }}
  .step-detail span {{ color: #e8e8f0; }}
  .reason {{ color: #ef4444; font-size: 12px; margin-top: 6px; padding: 8px 12px; background: #2a1020; border-radius: 6px; }}
</style>
</head>
<body>
<div class="container">
  <h1>{title}</h1>
  <p class="meta">{time} · {passed}/{total} 通过 · {duration}</p>

  <div class="summary">
    <div class="summary-card pass">
      <div class="num">{passed}</div>
      <div class="label">✅ 通过</div>
    </div>
    <div class="summary-card fail">
      <div class="num">{failed}</div>
      <div class="label">❌ 失败</div>
    </div>
    <div class="summary-card">
      <div class="num">{total}</div>
      <div class="label">📋 总计</div>
    </div>
  </div>

  {steps_html}

  <p class="meta" style="margin-top:40px;text-align:center">Generated by QualiAI</p>
</div>

<script>
document.querySelectorAll('.step-header').forEach(h => {{
  h.addEventListener('click', () => {{
    h.nextElementSibling.classList.toggle('open');
  }});
}});
</script>
</body>
</html>"""


class HTMLReporter:
    """生成 HTML 测试报告"""

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate(self, title: str, steps: list[dict], results: list[dict]) -> str:
        """生成 HTML 报告，返回文件路径"""
        passed = sum(1 for r in results if r.get("passed"))
        total = len(results)
        failed = total - passed
        total_duration = sum(r.get("duration", 0) for r in results)

        # 构建步骤 HTML
        steps_html = []
        action_icons = {
            "navigate": "🌐", "click": "🖱️", "type": "⌨️",
            "assert": "🔍", "wait": "⏳", "scroll": "📜", "error": "⚠️",
        }

        for i, (step, result) in enumerate(zip(steps, results)):
            action = step.get("action", "")
            desc = step.get("desc", "")
            passed_flag = result.get("passed", False)
            reason = result.get("reason", "")
            screenshot_b64 = result.get("screenshot", "")
            duration = result.get("duration", 0)
            url = result.get("url", "")

            icon = action_icons.get(action, "•")
            status_text = "PASS" if passed_flag else "FAIL"
            status_cls = "pass" if passed_flag else "fail"

            # 截图
            img_html = ""
            if screenshot_b64:
                img_html = f'<img src="data:image/png;base64,{screenshot_b64}" alt="步骤 {i+1} 截图" />'

            # 失败原因
            reason_html = ""
            if reason:
                reason_html = f'<div class="reason">❌ {reason}</div>'

            steps_html.append(f"""
    <div class="step">
      <div class="step-header">
        <div class="step-icon">{icon}</div>
        <div class="step-info">
          <div class="step-title">步骤 {i+1}: {action}</div>
          <div class="step-desc">{desc}</div>
        </div>
        <span class="step-status {status_cls}">{status_text}</span>
      </div>
      <div class="step-body">
        {img_html}
        {reason_html}
        <div class="step-detail">
          用时: {duration}s · URL: <span>{url}</span>
        </div>
      </div>
    </div>""")

        # 生成 HTML
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        duration_str = f"{total_duration:.1f}s"
        html = REPORT_TEMPLATE.format(
            title=title,
            time=timestamp,
            passed=passed,
            failed=failed,
            total=total,
            duration=duration_str,
            steps_html="\n".join(steps_html),
        )

        # 保存
        safe_name = title.replace(" ", "_").replace("/", "_")[:50] or "test"
        filename = f"{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        return os.path.abspath(filepath)
